# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    docker build -t deployment . 
  displayName: 'Build image'


- script: |
    docker run -e "USERNAME=${USERNAME}" -e "PASSWORD=${PASSWORD}" -e "TENANT=${TENANT}" --mount source=.,destination=/home/vscode/app deployment
  displayName: 'Deploy App'